### ISSUE TITLE
Missing R1-3 tag?

### ISSUE THREAD

**Issue by anjohnson** [areaDetector/NDDriverStdArrays#8]
Almost a year ago (12/19/18) there were commits to this repository with the subject 'Notes for R1-3' and the driver version number in NDDriverStdArrays.h was bumped, but no git tag was ever created for that version number. Those and later commits to this submodule have been pulled into the AreaDetector master branch several times since, for new releases of areaDetector.

It might be least confusing to retroactively create that tag at the point where the header version was updated and the notes added (although the notes actually say January XXX, 2018). To do that:
```sh
$ cd NDDriverStdArrays
$ git tag R1-3 9145906af
$ git push --tags
```

Note that the output from `git submodule status` shows when a submodule is checked out at a particular tag and also gives the number of commits since the last tag if there have been any, so you can easily tell which versions you have checked out.

**Comment by MarkRivers** [comment]
I have fixed this as Andrew suggested.
